name: Go

on:
  commit:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: implementation.go cmd/example/main.go
	         mkdir -p out
	         go build -o out/example ./cmd/example

    - name: Test
      run: 	go vet ./...
	          go test ./...
